### ISSUE TITLE
Gemfile.lock should not be on version control

### ISSUE THREAD

**Issue by phrb** [acessoajustica/acessoajustica#3]
I think we should remove the Gemfile.lock from version control, because everytime I build the project, bundler can't rewrite it, and I have to remove it and start the build again.

What are your opinions on this?

**Comment by Dhinihan** [comment]
Maybe this happens becouse of Docker, becouse the proupose of the .lock file is to maintain the same development enviroment to all programers. If we have different gems versions, some compatibility issues might occur and won't be necessarily obvius to detect.

**Comment by renatocf** [comment]
I considered that yestarday, but @Dhinihan argued that it should be versioned, as it is also responsible for increasing the speed of build. Perharps the best is to run:

``` bash
$ docker-compose run web bundle update
```

So bundle will check, inside all conteiners, all existent bundles and update them accordingly.

**Comment by Dhinihan** [comment]
I think @renatocf misunderstood me, the speed advantage is to use that bundle update command opposite to use bundle install via docker-compose build. The advantage of the lock file is to assure that everyone is using the same versions of the gems.

**Comment by phrb** [comment]
Maybe we could tell bundler to always get the latest versions of the gems, so everyone would get the same build, and then we could remove the .lock from version control. 

My point is that having to remove the .lock file before building seems weird, and is a possible source of weird errors. (as we've seen wednesday)

#### My argument for a "lock-free-startup-script" for the dev workflow

Since running

```
$ docker-compose build
```

Without a previous lock already creates a correct one (hopefully), and since

```
$ docker-compose up
```

Won't work every time because of outdated containers, or when changing branches, I suggest we always run the sequence:

```
sudo docker stop $(sudo docker ps -a -q)    # Stops old (outdated) containers.
sudo docker rm $(sudo docker ps -a -q)      # Remove old containers.
sudo docker rmi [project_name]_web:latest   # Removes old project image.
sudo docker-compose build                   # Builds a new image.
sudo docker-compose run web rake db:create  # Creates test database.
sudo docker-compose run web rake db:migrate # Runs migrations.
sudo docker-compose run web rake spec       # Runs tests.
sudo docker-compose up                      # Starts the app.
```

These commands should be (in my opinion) the starting point of everybody's workflow. If everyone agrees, I can write the script and commit it. This would allow us to remove the .lock file from version control and, provided we tell bundler to always use the latest versions (or a fixed one for each gem), make all environments have the same .lock.

We could start a new day with:

```
$ git checkout [branch_name]
$ git pull
$ ./scripts/init.sh
```

No worries with locks, no weird docker commands to remember. What the team thinks about this?

**Comment by renatocf** [comment]
It's nice to have this script as a guarantee to make everything works. But I think it's a waste donwloading all gems again every time we'll work with the project.

My suggestion is to create 2 scripts (names can be changed):
- `start.sh`: just stops old containers and runs `docker-compose up`
- `restart.sh`: rebuilds all project from the scratch with `docker-compose build`

If someone's build fails, we run `restart.sh`. Otherwise, we spare some time without rebuilding everything. What do you think? Or do you believe the waste will be insignifant?

**Comment by phrb** [comment]
Nice idea! I'm editing the build script now, and I realized there's a lot of useless things there. We don't have to recreate our bare rails app. We can just clone the repository and build directly. I'll start writing those simple scripts, and we can give them a run tomorrow.

Also, I'm removing gem installing code from the build script, since it is already done in our rails app.

**Comment by Dhinihan** [comment]
@phrb, you shouldn't delete the lock file. If the bundle install doesn't work, just do:

``` bash
docker-composer run web bundle update
```

I think that the correct flow is to install the gems when you build the application for the first time, and then only update if you are adding a new gem, or checking for new versions.

**Comment by phrb** [comment]
@Dhinihan I'm adding the bundle update as an option for the script. Let me see if I got it right:

We should run

```
sudo docker-compose run web bundle update
```

When there are already running containers, and we just want to update, right?
Because if we remove old containers, this is not going to work, it will have to install all gems again.

I'm trying to build everything here using a test script. I'll bring it ready tomorrow so everybody can test.

**Comment by Dhinihan** [comment]
@phrb Yes, but you don't need to delete the lock file, unless the install fails. Theorically, the person who has committed the lock file worked with it.

**Comment by phrb** [comment]
Hi!

The script is up: fcb4e1ec392897d8377ba0913606a2d3d43cc6ff.

Usage:

```
# Builds the image from scratch, creates a new Gemfile.lock, runs all tests.
./scripts/init.sh all 

#  Runs bundle update, does not remove containers or Gemfile.lock, runs all tests and migrations.
./scripts/init.sh update

# Stops and removes all containers.
./scripts/init.sh clean

# Restarts the app container if it's running, starts it otherwise.
./scripts/init.sh restart

# Runs migrations and starts the app container.
./scripts/init.sh run

# Runs the migrations.
./scripts/init.sh migrate

# Runs all migrations and tests.
./scripts/init.sh test
```

I think we won't have to worry about Gemfile.lock anymore. It can stay in the repo, and be re-created as needed, if the build fails. The script provides a way to run bundle updates, testing, migrating, building and running.
